{
  config,
  lib,
  pkgs,
  options,
  user,
  hyprland,
  ...
}:
let
  cc = import ../lib/comcreate-palette.nix;
  cfgHome = config.xdg.configHome;

  # hyprctl from the same 0.55.x flake build the compositor runs, so the IPC
  # protocol matches. In 0.55, `hyprctl dispatch` takes the Lua dispatcher form.
  hyprctl = "${hyprland.packages.${pkgs.system}.hyprland}/bin/hyprctl";

  # comcreate is now the default waybar config (~/.config/waybar/{config,style.css}),
  # so launch it bare — no -c/-s needed.
  waybarCmd = "waybar";

  # Power menu (Hyprland variant of the niri power-menu — uses hyprlock + hyprctl)
  hypr-power-menu = pkgs.writeShellScriptBin "hypr-power-menu" ''
    CHOICE=$(printf "Lock\nLogout\nSuspend\nReboot\nShutdown" \
      | ${pkgs.fuzzel}/bin/fuzzel --dmenu --config ${cfgHome}/fuzzel/comcreate.ini --prompt="⏻  ")
    case "$CHOICE" in
      Lock)     ${pkgs.hyprlock}/bin/hyprlock ;;
      Logout)   ${hyprctl} dispatch 'hl.dsp.exit()' ;;
      Suspend)  systemctl suspend ;;
      Reboot)   systemctl reboot ;;
      Shutdown) systemctl poweroff ;;
    esac
  '';

  # Wallpaper picker (mirrors niri's; `find -L` is required for the nix-symlinked ~/wallpapers)
  hypr-wallpaper-pick = pkgs.writeShellScriptBin "hypr-wallpaper-pick" ''
    PICK=$(find -L ~/wallpapers -type f \( -name '*.png' -o -name '*.jpg' -o -name '*.jpeg' \) \
      | ${pkgs.fuzzel}/bin/fuzzel --dmenu --config ${cfgHome}/fuzzel/comcreate.ini --prompt="Wallpaper: ")
    [ -n "$PICK" ] && cp "$PICK" ~/wallpaper.png \
      && ${pkgs.swww}/bin/swww img "$PICK" --transition-type grow --transition-duration 1
  '';
in
{
  config = lib.mkMerge [
    {
      home.packages = [
        hypr-power-menu
        hypr-wallpaper-pick
      ];

      # Hyprland 0.55 dropped hyprlang in favor of Lua (`~/.config/hypr/hyprland.lua`).
      # The home-manager `wayland.windowManager.hyprland` module only emits the old
      # hyprlang `.conf` (which 0.55 ignores), so we bypass it and write the Lua
      # config directly. The compositor + portal come from modules/desktop-hyprland.nix.
      xdg.configFile."hypr/hyprland.lua".text = ''
        -- comcreate Hyprland session — Lua config (Hyprland 0.55+)
        -- Generated by home/hyprland-comcreate.nix. Hand-converted from the former
        -- hyprlang settings; see the wiki for the hl.* API.

        local mod = "SUPER"

        -- ── Monitors ──
        hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

        -- ── Environment ──
        -- NVIDIA GBM_BACKEND/__GLX_VENDOR_LIBRARY_NAME etc. are already global
        -- (modules/nvidia.nix → environment.sessionVariables); only cursor sizes here.
        hl.env("XCURSOR_SIZE", "24")
        hl.env("HYPRCURSOR_SIZE", "24")

        -- ── Core options ──
        hl.config({
          cursor = {
            no_hardware_cursors = 1, -- 0.55: int (1 = never use hw cursors), was bool
          },
          general = {
            gaps_in = 6,
            gaps_out = 12,
            border_size = 2,
            ["col.active_border"] = { colors = { "rgba(7b7bffee)", "rgba(72b8ffee)" }, angle = 45 }, -- azure gradient
            ["col.inactive_border"] = "rgba(211e1aaa)",
            layout = "dwindle",
            allow_tearing = false,
            resize_on_border = true,
          },
          dwindle = {
            pseudotile = true,
            preserve_split = true,
          },
          -- ── Glassy blur + rounding + soft shadows ──
          decoration = {
            rounding = 14,
            active_opacity = 0.97,
            inactive_opacity = 0.90,
            dim_inactive = true,
            dim_strength = 0.08,
            blur = {
              enabled = true,
              size = 8,
              passes = 3,
              new_optimizations = true,
              ignore_opacity = true,
              vibrancy = 0.18,
              noise = 0.02,
            },
            shadow = {
              enabled = true,
              range = 18,
              render_power = 3,
              color = "rgba(00000055)",
            },
          },
          animations = {
            enabled = true,
          },
          input = {
            kb_layout = "us",
            repeat_delay = 200,
            repeat_rate = 35,
            follow_mouse = 1,
            sensitivity = 0,
            touchpad = {
              natural_scroll = true,
              tap_to_click = true, -- 0.55 lua name (was `tap-to-click` in hyprlang)
            },
          },
          gestures = {
            workspace_swipe_distance = 300,
          },
          misc = {
            disable_hyprland_logo = true,
            disable_splash_rendering = true,
            focus_on_activate = true,
            -- `vfr` moved to debug.vfr in newer versions and defaults to true; dropped.
          },
          ecosystem = {
            no_update_news = true,
          },
        })

        -- ── Animation curves + tree (replaces the old bezier/animation arrays) ──
        hl.curve("easeOutQuad", { type = "bezier", points = { { 0.25, 0.46 }, { 0.45, 0.94 } } })
        hl.curve("snappy",      { type = "bezier", points = { { 0.2, 1.0 },   { 0.3, 1.0 } } })

        hl.animation({ leaf = "windows",    enabled = true, speed = 2.5, curve = "snappy",      style = "popin 6%" })
        hl.animation({ leaf = "windowsOut", enabled = true, speed = 2.5, curve = "easeOutQuad", style = "popin 6%" })
        hl.animation({ leaf = "border",     enabled = true, speed = 5,   curve = "easeOutQuad" })
        hl.animation({ leaf = "fade",       enabled = true, speed = 3,   curve = "easeOutQuad" })
        hl.animation({ leaf = "workspaces", enabled = true, speed = 3,   curve = "snappy",      style = "slide" })

        -- ── Touchpad gesture: 3-finger horizontal swipe → switch workspace ──
        hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

        -- ── Layer rules: frost the bar / launcher / notifications ──
        hl.layer_rule({ match = { namespace = "waybar" },                     blur = true, ignore_alpha = 0 })
        hl.layer_rule({ match = { namespace = "launcher" },                   blur = true, ignore_alpha = 0 }) -- fuzzel's namespace
        hl.layer_rule({ match = { namespace = "swaync-control-center" },      blur = true, ignore_alpha = 0 })
        hl.layer_rule({ match = { namespace = "swaync-notification-window" }, blur = true, ignore_alpha = 0 })

        -- ── Window rules ──
        hl.window_rule({ match = { class = "^(pavucontrol)$" },           float = true })
        hl.window_rule({ match = { class = "^(TUI.float)$" },             float = true })
        hl.window_rule({ match = { title = "^(Picture-in-Picture)$" },    float = true })
        hl.window_rule({ match = { class = "^(com.mitchellh.ghostty)$" }, opacity = "0.94 0.88" })
        hl.window_rule({ match = { class = ".*" },                        suppress_event = "maximize" })

        -- ── Keybinds ──
        -- Programs
        hl.bind(mod .. " + RETURN", hl.dsp.exec_cmd("ghostty"))
        hl.bind(mod .. " + SPACE",  hl.dsp.exec_cmd("fuzzel --config ${cfgHome}/fuzzel/comcreate.ini"))
        hl.bind(mod .. " + V",      hl.dsp.exec_cmd("cliphist list | fuzzel --dmenu --config ${cfgHome}/fuzzel/comcreate.ini | cliphist decode | wl-copy"))
        hl.bind(mod .. " + SHIFT + S", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | satty -f -]]))
        hl.bind(mod .. " + SHIFT + P", hl.dsp.exec_cmd("grim - | wl-copy"))
        hl.bind("Print",            hl.dsp.exec_cmd([[grim ~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png]]))

        -- Window management
        hl.bind(mod .. " + Q", hl.dsp.window.close())
        hl.bind(mod .. " + W", hl.dsp.window.close())
        hl.bind(mod .. " + F",         hl.dsp.window.fullscreen({ mode = "maximized" })) -- maximize (keep gaps/bar)
        hl.bind(mod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen" })) -- true fullscreen
        hl.bind(mod .. " + T", hl.dsp.window.float())
        hl.bind(mod .. " + C", hl.dsp.window.center())
        hl.bind(mod .. " + P", hl.dsp.window.pseudo())
        hl.bind(mod .. " + S", hl.dsp.layout("togglesplit")) -- dwindle layout message

        -- Vim + arrow focus
        hl.bind(mod .. " + H", hl.dsp.focus({ direction = "l" }))
        hl.bind(mod .. " + J", hl.dsp.focus({ direction = "d" }))
        hl.bind(mod .. " + K", hl.dsp.focus({ direction = "u" }))
        hl.bind(mod .. " + L", hl.dsp.focus({ direction = "r" }))
        hl.bind(mod .. " + left",  hl.dsp.focus({ direction = "l" }))
        hl.bind(mod .. " + down",  hl.dsp.focus({ direction = "d" }))
        hl.bind(mod .. " + up",    hl.dsp.focus({ direction = "u" }))
        hl.bind(mod .. " + right", hl.dsp.focus({ direction = "r" }))

        -- Vim + arrow move
        hl.bind(mod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
        hl.bind(mod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
        hl.bind(mod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
        hl.bind(mod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))
        hl.bind(mod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "l" }))
        hl.bind(mod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "d" }))
        hl.bind(mod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "u" }))
        hl.bind(mod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))

        -- Resize (relative; percent of dimension)
        hl.bind(mod .. " + minus", hl.dsp.window.resize({ x = "-10%", y = "0", relative = true }))
        hl.bind(mod .. " + equal", hl.dsp.window.resize({ x = "10%",  y = "0", relative = true }))

        -- Workspaces 1-10 (focus + move-window-to)
        for i = 1, 10 do
          local key = (i == 10) and "0" or tostring(i)
          hl.bind(mod .. " + " .. key,           hl.dsp.focus({ workspace = i }))
          hl.bind(mod .. " + SHIFT + " .. key,   hl.dsp.window.move({ workspace = i, follow = true }))
        end
        hl.bind(mod .. " + TAB",         hl.dsp.focus({ workspace = "e+1" }))
        hl.bind(mod .. " + SHIFT + TAB", hl.dsp.focus({ workspace = "e-1" }))

        -- Notifications (swaync)
        hl.bind(mod .. " + comma",         hl.dsp.exec_cmd("swaync-client -d -sw")) -- dismiss latest
        hl.bind(mod .. " + SHIFT + comma", hl.dsp.exec_cmd("swaync-client -C -sw")) -- close all
        hl.bind(mod .. " + N",             hl.dsp.exec_cmd("swaync-client -t -sw")) -- toggle panel

        -- Control panels
        hl.bind(mod .. " + CTRL + A", hl.dsp.exec_cmd("pavucontrol"))
        hl.bind(mod .. " + CTRL + B", hl.dsp.exec_cmd("ghostty --class=TUI.float -e bluetui"))
        hl.bind(mod .. " + CTRL + T", hl.dsp.exec_cmd("ghostty -e btop"))
        hl.bind(mod .. " + CTRL + D", hl.dsp.exec_cmd("ghostty -e rice-dashboard"))

        -- Utilities
        hl.bind(mod .. " + CTRL + L",  hl.dsp.exec_cmd("hyprlock"))
        hl.bind(mod .. " + SHIFT + X", hl.dsp.exec_cmd("hypr-power-menu"))
        hl.bind(mod .. " + SHIFT + W", hl.dsp.exec_cmd("hypr-wallpaper-pick"))
        hl.bind(mod .. " + SHIFT + SPACE", hl.dsp.exec_cmd("pkill waybar || ${waybarCmd}"))
        hl.bind(mod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))
        hl.bind(mod .. " + CTRL + N",  hl.dsp.exec_cmd("pkill wlsunset || wlsunset -t 3500 -T 6500 -l 40.76 -L -111.89"))
        hl.bind(mod .. " + ALT + L",   hl.dsp.exec_cmd("~/.local/bin/toggle-dictation.sh"))

        -- Session
        hl.bind(mod .. " + SHIFT + E", hl.dsp.exit())

        -- Repeating volume/brightness (via swayosd for the OSD)
        hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise"), { repeating = true })
        hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"), { repeating = true })
        hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("swayosd-client --brightness raise"),    { repeating = true })
        hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("swayosd-client --brightness lower"),    { repeating = true })

        -- Locked binds (work while the lock screen is active)
        hl.bind("XF86AudioMute",    hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { locked = true })
        hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"),  { locked = true })
        hl.bind("XF86AudioPlay",    hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
        hl.bind("XF86AudioNext",    hl.dsp.exec_cmd("playerctl next"),       { locked = true })
        hl.bind("XF86AudioPrev",    hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

        -- Mouse drag/resize
        hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
        hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

        -- ── Autostart (was exec-once) ──
        hl.on("hyprland.start", function()
          -- Import env into systemd/dbus, then bounce the portals (mirrors the niri startup line)
          hl.exec_cmd([[bash -c 'systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE NIXOS_OZONE_WL GBM_BACKEND NVD_BACKEND LIBVA_DRIVER_NAME __GLX_VENDOR_LIBRARY_NAME && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE && systemctl --user start hyprland-session.target && systemctl --user restart xdg-desktop-portal-hyprland xdg-desktop-portal 2>/dev/null']])
          hl.exec_cmd("swww-daemon")
          hl.exec_cmd("wl-paste --watch cliphist store")
          hl.exec_cmd("swayosd-server")
          hl.exec_cmd("${waybarCmd}")
          hl.exec_cmd("swaync")
          hl.exec_cmd("hypridle")
          hl.exec_cmd("wlsunset -t 3500 -T 6500 -l 40.76 -L -111.89")
          hl.exec_cmd("sleep 1 && swww img ${config.home.homeDirectory}/wallpaper.png --transition-type grow --transition-duration 1")
        end)
      '';

      # ── Waybar: dedicated comcreate config/style (separate filenames so it never clobbers
      #    the Stylix-themed default waybar that the niri session uses) ──
      # Stylix used to own ~/.config/waybar/style.css (for the now-removed plain-Niri
      # bar); disable that target so our comcreate style.css is the sole default.
      stylix.targets.waybar.enable = false;

      xdg.configFile."waybar/config".text = builtins.toJSON {
        layer = "top";
        position = "top";
        height = 34;
        spacing = 6;
        margin-top = 8;
        margin-left = 12;
        margin-right = 12;
        modules-left = [ "hyprland/workspaces" ];
        modules-center = [ "clock" ];
        modules-right = [ "cpu" "memory" "network" "pulseaudio" "tray" ];

        "hyprland/workspaces" = {
          format = "{name}";
          on-click = "activate";
          all-outputs = true;
        };
        clock = {
          format = "{:%H:%M  ·  %a %b %d}";
          tooltip-format = "<tt>{calendar}</tt>";
        };
        cpu = {
          format = "cpu {usage}%";
          interval = 5;
        };
        memory = {
          format = "mem {percentage}%";
          interval = 5;
        };
        network = {
          format-wifi = "{essid}";
          format-ethernet = "eth";
          format-disconnected = "offline";
        };
        pulseaudio = {
          format = "vol {volume}%";
          format-muted = "muted";
          on-click = "pavucontrol";
        };
        tray = {
          spacing = 10;
        };
      };

      xdg.configFile."waybar/style.css".text = ''
        * {
          font-family: "JetBrainsMono Nerd Font", monospace;
          font-size: 13px;
          border: none;
          border-radius: 0;
          min-height: 0;
        }
        window#waybar {
          background: transparent;
          color: ${cc.base05};
        }
        /* Floating frosted-glass module groups (Hyprland layer blur does the frosting) */
        .modules-left,
        .modules-center,
        .modules-right {
          background: rgba(27, 25, 23, 0.55); /* base01 @ 55% */
          border: 1px solid rgba(123, 123, 255, 0.18); /* faint azure edge */
          border-radius: 14px;
          padding: 1px 8px;
          margin: 0 4px;
        }
        #workspaces button {
          color: ${cc.base04};
          padding: 0 9px;
          margin: 2px 2px;
          border-radius: 10px;
        }
        #workspaces button.active {
          color: ${cc.base05};
          background: rgba(123, 123, 255, 0.14);
          box-shadow: inset 0 -2px ${cc.accent}; /* azure underline */
        }
        #workspaces button:hover {
          background: rgba(232, 228, 223, 0.06);
          box-shadow: none;
        }
        #clock {
          color: ${cc.base05};
          font-weight: bold;
          padding: 0 10px;
        }
        #cpu,
        #memory,
        #network,
        #pulseaudio {
          color: ${cc.base06};
          padding: 0 9px;
        }
        #pulseaudio.muted {
          color: ${cc.base03};
        }
        #tray {
          padding: 0 6px;
        }
      '';

      # ── fuzzel: comcreate launcher (separate config path; launched via --config) ──
      xdg.configFile."fuzzel/comcreate.ini".text = ''
        [main]
        font=JetBrainsMono Nerd Font:size=12
        prompt=>
        icon-theme=Papirus-Dark
        lines=10
        width=36
        horizontal-pad=20
        vertical-pad=16
        inner-pad=10
        layer=overlay

        [colors]
        background=141210ee
        text=e8e4dfff
        prompt=8a847cff
        placeholder=6b655dff
        input=e8e4dfff
        match=7b7bffff
        selection=211e1aff
        selection-text=f2efe9ff
        selection-match=72b8ffff
        border=7b7bffff

        [border]
        width=2
        radius=14
      '';

      # ── swaync: glassy notification center ──
      xdg.configFile."swaync/config.json".text = builtins.toJSON {
        positionX = "right";
        positionY = "top";
        layer = "overlay";
        control-center-layer = "top";
        control-center-width = 380;
        control-center-margin-top = 10;
        control-center-margin-bottom = 10;
        control-center-margin-right = 10;
        control-center-margin-left = 10;
        notification-window-width = 380;
        timeout = 8;
        timeout-low = 5;
        timeout-critical = 0;
        fit-to-screen = true;
        widgets = [ "title" "dnd" "notifications" ];
        widget-config = {
          title = {
            text = "comcreate";
            clear-all-button = true;
            button-text = "clear";
          };
          dnd = {
            text = "do not disturb";
          };
        };
      };

      xdg.configFile."swaync/style.css".text = ''
        * {
          font-family: "JetBrainsMono Nerd Font", monospace;
        }
        .control-center {
          background: rgba(20, 18, 16, 0.7);
          color: ${cc.base05};
          border: 1px solid rgba(123, 123, 255, 0.18);
          border-radius: 16px;
          margin: 8px;
          padding: 12px;
        }
        .notification-row .notification-background .notification {
          background: rgba(27, 25, 23, 0.78);
          color: ${cc.base05};
          border: 1px solid rgba(123, 123, 255, 0.14);
          border-radius: 14px;
          margin: 6px 4px;
          padding: 4px;
        }
        .notification-row .notification-background .notification.critical {
          border-color: ${cc.base08};
        }
        .widget-title {
          color: ${cc.base05};
          font-weight: bold;
          padding: 4px 8px;
        }
        .widget-title > button {
          background: rgba(123, 123, 255, 0.14);
          color: ${cc.base05};
          border-radius: 10px;
          padding: 2px 10px;
        }
        .widget-dnd {
          color: ${cc.base04};
          padding: 4px 8px;
        }
        .notification-action {
          background: rgba(27, 25, 23, 0.6);
          color: ${cc.base05};
          border-radius: 10px;
        }
      '';

      # ── hyprlock: frosted blur-over-wallpaper lock ──
      xdg.configFile."hypr/hyprlock.conf".text = ''
        background {
          monitor =
          path = ${config.home.homeDirectory}/wallpaper.png
          blur_passes = 3
          blur_size = 8
          noise = 0.02
          contrast = 0.9
          brightness = 0.7
          vibrancy = 0.18
        }

        input-field {
          monitor =
          size = 280, 50
          outline_thickness = 2
          dots_size = 0.25
          dots_spacing = 0.3
          outer_color = rgba(7b7bffee)
          inner_color = rgba(1b1917cc)
          font_color = rgba(e8e4dfff)
          placeholder_text = <span foreground="##8a847c">comcreate</span>
          rounding = 14
          fade_on_empty = false
          position = 0, -40
          halign = center
          valign = center
        }

        label {
          monitor =
          text = $TIME
          font_size = 64
          font_family = JetBrainsMono Nerd Font
          color = rgba(e8e4dfff)
          position = 0, 120
          halign = center
          valign = center
        }

        label {
          monitor =
          text = cmd[update:60000] date +"%A, %B %d"
          font_size = 18
          font_family = JetBrainsMono Nerd Font
          color = rgba(c5bfb5cc)
          position = 0, 60
          halign = center
          valign = center
        }
      '';

      # ── hypridle: lock → dpms off → suspend ──
      # hypridle/hyprlock keep their own hyprlang config (unaffected by Hyprland's
      # Lua switch), but their `dpms` calls go through hyprctl to Hyprland 0.55,
      # which now takes the Lua dispatcher form: `hyprctl dispatch 'hl.dsp.dpms(...)'`.
      xdg.configFile."hypr/hypridle.conf".text = ''
        general {
          lock_cmd = pidof hyprlock || hyprlock
          before_sleep_cmd = loginctl lock-session
          after_sleep_cmd = ${hyprctl} dispatch 'hl.dsp.dpms({ action = "on" })'
        }

        listener {
          timeout = 300
          on-timeout = loginctl lock-session
        }

        listener {
          timeout = 360
          on-timeout = ${hyprctl} dispatch 'hl.dsp.dpms({ action = "off" })'
          on-resume = ${hyprctl} dispatch 'hl.dsp.dpms({ action = "on" })'
        }

        listener {
          timeout = 600
          on-timeout = systemctl suspend
        }
      '';
    }

    # Opt the Hyprland session OUT of global Stylix so it carries the comcreate palette —
    # same precedent as stylix.targets.niri.enable=false in home/shell.nix. Guarded because
    # stylix 25.11 may not declare a `hyprland` target (research couldn't confirm); if absent,
    # Stylix never touches hypr/ anyway and the hand-coded colors win regardless.
    (lib.optionalAttrs (options.stylix.targets ? hyprland) {
      stylix.targets.hyprland.enable = false;
    })
  ];
}
