{ config, pkgs, user, ... }:

let
  shellAliases = {
    # Navigation
    ".." = "cd ..";
    "..." = "cd ../..";

    # Git
    gs = "git status";
    ga = "git add";
    gc = "git commit";
    gp = "git push";
    gl = "git log --oneline --graph";
    gd = "git diff";
    gb = "git branch";

    # Docker
    dc = "docker-compose";
    dps = "docker ps";
    dimg = "docker images";
    dlog = "docker logs";

    # Nix
    rebuild = "sudo nixos-rebuild switch --flake ~/dotfiles#$(hostname | tr 'A-Z' 'a-z')";
    nrs = "sudo nixos-rebuild switch --flake ~/dotfiles#$(hostname | tr 'A-Z' 'a-z')";
    update = "sudo nixos-rebuild switch --flake ~/dotfiles#$(hostname | tr 'A-Z' 'a-z') --upgrade";

    # Modern replacements
    ls = "eza --icons";
    ll = "eza -la --icons";
    cat = "bat";
    grep = "rg";

    # Ollama (runs in podman container as root)
    ollama = "sudo podman exec -it ollama ollama";
    ai = "sudo podman exec -it ollama ollama run qwen3.5:9b";

    # OpenClaw
    claw = "openclaw";
  };
in
{
  programs.fish = {
    enable = true;
    inherit shellAliases;
    interactiveShellInit = ''
      set -g fish_greeting
      fish_add_path $HOME/.local/bin $HOME/.cargo/bin

      # Load matugen-generated fzf colors
      if test -f $HOME/.config/fzf/colors
        set -gx FZF_DEFAULT_OPTS (cat $HOME/.config/fzf/colors | string collect)
      end

      # tmux dev layout
      function dev
        tmux new-session -d -s dev -c (pwd)
        tmux split-window -h -p 40
        tmux split-window -v -p 50
        tmux select-pane -t 1
        tmux send-keys -t dev:1.1 "nvim" Enter
        tmux select-pane -t dev:1.1
        tmux attach -t dev
      end
    '';
  };

  programs.bash = {
    enable = true;
    inherit shellAliases;
    initExtra = ''
      export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
      # Load matugen-generated fzf colors
      [ -f "$HOME/.config/fzf/colors" ] && export FZF_DEFAULT_OPTS="$(cat "$HOME/.config/fzf/colors")"
    '';
  };

  # Starship prompt — config generated by matugen template (see theme.nix)
  programs.starship.enable = true;

  # fzf integration — colors loaded from matugen-generated file at runtime
  programs.fzf = {
    enable = true;
    enableBashIntegration = true;
    enableFishIntegration = true;
  };

  # zoxide (smart cd)
  programs.zoxide = {
    enable = true;
    enableBashIntegration = true;
    enableFishIntegration = true;
  };

  # direnv for per-project nix shells
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };
}
